// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Models;

namespace WebApi.Migrations
{
    [DbContext(typeof(TshirtDbcontext))]
    partial class TshirtDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.T_shirts", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("color")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("made")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("price")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("size")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("style")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("T_Shirt");
                });
#pragma warning restore 612, 618
        }
    }
}
